tasks:
  package:
    name: Package App
    command: |
      ## ?? What's my expected path?
      cd /workspace/flex-petclinic
      ./mvnw -Dmaven.test.skip=true -B package
    triggeredBy:
      - manual
  release:
    name: Release
    dependsOn:
      - package
    triggeredBy:
      - manual
    command: |
      source ./set_gh_token.sh
      REPO="meysholdt/flex-petclinic"
      TAG_NAME="v1.0.0"
      RELEASE_TITLE="Release $TAG_NAME"
      RELEASE_NOTES="Release of app.jar"
      FILE_NAME="./target/spring-petclinic-3.3.0-SNAPSHOT.jar"

      # Create the release
      gh release create "$TAG_NAME" "$FILE_NAME" \
          --repo "$REPO" \
          --title "$RELEASE_TITLE" \
          --notes "$RELEASE_NOTES"


#                    --verify-tag
