services:
  app:
    name: App
    dependsOn:
      - postgres
    trigger:
      - onStart
      - manual
    commands:
      start: |
        ./mvnw spring-boot:run -Dspring-boot.run.profiles=postgres
      ready:
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q "200"

  postgres:
    name: Postgres
    trigger:
      - onStart
      - manual
    commands:
      start: |
        docker-compose --profile postgres up
      ready:
        PGPASSWORD="petclinic" psql -h localhost -U petclinic -d petclinic -c '\q' >/dev/null 2>&1  

tasks:
  package:
    name: Package
    command: |
      cd /workspace/flex-petclinic
      ./mvnw -Dmaven.test.skip=true -B package
    triggeredBy:
      - manual
  release:
    name: Release
    dependsOn:
      - package
    triggeredBy:
      - manual
    command: |
      source ./set_gh_token.sh
      REPO="meysholdt/flex-petclinic"
      TAG_NAME="v1.0.0"
      RELEASE_TITLE="Release $TAG_NAME"
      RELEASE_NOTES="Release of app.jar"
      FILE_NAME="./target/spring-petclinic-3.3.0-SNAPSHOT.jar"

      # Create the release
      gh release create "$TAG_NAME" "$FILE_NAME" \
          --repo "$REPO" \
          --title "$RELEASE_TITLE" \
          --notes "$RELEASE_NOTES"


#                    --verify-tag
